import { BasePage } from '@core/base/BasePage';
import { byCss, byRole, LocatorDescriptor } from '@core/locators/SelfHealingLocator';

/**
 * Generated by Playwright Locator Inspector from a recorded session.
 * Review element names, the pageIdentifier, and method names before
 * committing — this is a strong first draft, not a final page object.
 */
export class LedgermasterPage extends BasePage {
  protected readonly pageUrl = '/ledgermaster/';

  protected readonly pageIdentifier: LocatorDescriptor = {
    // TODO: consider pointing this at a more definitive "page has loaded" element.
    name: 'Customers link',
    strategies: [
      byCss('div:nth-of-type(2) > ul > li:nth-of-type(1) > a'),
      byRole('link', { name: 'Customers' }),
    ],
  };

  private readonly customersLink: LocatorDescriptor = {
    name: 'Customers link',
    strategies: [
      byCss('div:nth-of-type(2) > ul > li:nth-of-type(1) > a'),
      byRole('link', { name: 'Customers' }),
    ],
  };

  private readonly button: LocatorDescriptor = {
    name: 'Button',
    strategies: [
      byCss('tr:nth-of-type(1) > td:nth-of-type(1) > button'),
      byRole('button'),
    ],
  };

  private readonly 200539165642435Link: LocatorDescriptor = {
    name: '200539165642435 link',
    strategies: [
      byCss('div:nth-of-type(1) > table > tbody > tr > td:nth-of-type(1) > a:nth-of-type(1)'),
      byRole('link', { name: '200539165642435' }),
    ],
  };

  private readonly accountsLink: LocatorDescriptor = {
    name: 'Accounts link',
    strategies: [
      byCss('span:nth-of-type(2) > li > a'),
      byRole('link', { name: 'Accounts' }),
    ],
  };

  async clickCustomersLink(): Promise<void> {
    await this.click(this.customersLink);
  }

  async clickButton(): Promise<void> {
    await this.click(this.button);
  }

  async click200539165642435Link(): Promise<void> {
    await this.click(this.200539165642435Link);
  }

  async clickAccountsLink(): Promise<void> {
    await this.click(this.accountsLink);
  }
}
