import { test, expect } from '@core/fixtures';
// Generated by Playwright Locator Inspector.
// 1. Save the companion page object as src/pages/LedgermasterPage.ts
// 2. Save this file as tests/e2e/ledgermaster.spec.ts
// 3. (Optional but recommended) register LedgermasterPage in
//    src/core/fixtures/pageFixtures.ts so future specs can destructure
//    it as a fixture instead of constructing it inline:
//
//      ledgermasterPage: async ({ page }, use) => { await use(new LedgermasterPage(page)); },
//
import { LedgermasterPage } from '../../src/pages/LedgermasterPage';

test.describe('Recorded flow', () => {
  test('recorded scenario — rename me', async ({ page }) => {
    const ledgermaster = new LedgermasterPage(page);

    await ledgermaster.goto();
    await ledgermaster.clickCustomersLink();
    await page.goto('https://plus.netxd.com/ledgermaster/#/customerlist'); // TODO: prefer a relative path via the environment baseUrl
    await ledgermaster.clickButton();
    await ledgermaster.click200539165642435Link();
    await page.goto('https://plus.netxd.com/ledgermaster/#/account/accountviewreason/7830002'); // TODO: prefer a relative path via the environment baseUrl
    await ledgermaster.clickAccountsLink();
    await page.goto('https://plus.netxd.com/ledgermaster/#/accountlist'); // TODO: prefer a relative path via the environment baseUrl
  });
});
